### ISSUE TITLE
Unstable

### ISSUE THREAD

**Issue by Sticknar-syx** [kres0345/Metasploit-GUI-for-Windows#3]
this entire project is very unstable, Porely  contruscted code. No hate to dev, but this need some work:(

**Comment by krestenlaust** [comment]
No offense taken, This is a very old project, I made it when I was 15 years old. If I were to remake this project, I am confident that the code would be much better. Safe to say I won't remake it or make something similar, with [recent development](https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux-2/) in Windows Subsystem for Linux (support for Linux GUI applications in Windows), there is no need for a Windows-specific tool much longer.
